name: Deploy

on:
  push:
    branches:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Push to gh-pages
        run: |
          git subtree push --prefix json_to_pydantic/static origin gh-pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
